[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
timemarket = "Gz7jdgqsn3R8mBrthEx5thAFYdM369kHN7wMTY3PKhty"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
deploy = "anchor deploy -p timemarket"
deploy_timemarket = "anchor build -p timemarket && anchor deploy -p timemarket"