[programs.localnet]
my_program = "4xVJq8m...ReplaceWithYourKey..."
timemarket = "TmMkt11111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor build && anchor deploy"
