name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        with:
          node-version: 20

      # Use dependency caching only when lockfile exists
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack and pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.6.0 --activate

      - name: Install deps (no lockfile)
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        run: pnpm install

      - name: Install deps (frozen lockfile)
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: pnpm -r build
