name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Ensure pnpm store is writable on GitHub runners and overrides repo .npmrc
      npm_config_store_dir: ${{ runner.temp }}/pnpm-store

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
          run_install: false

      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        with:
          node-version: 20

      # Install pnpm via Corepack before enabling cache logic that calls `pnpm`
      - name: Enable Corepack and pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.6.0 --activate
          pnpm -v

      # Override any repo-level .npmrc store-dir with a safe, writable path
      - name: Configure pnpm store path
        run: |
          pnpm config set store-dir ${{ runner.temp }}/pnpm-store
          pnpm store path

      # Now that pnpm is present, enable pnpm cache (uses `pnpm store path`)
      - name: Setup Node (enable pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps (no lockfile)
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        run: pnpm install

      - name: Install deps (frozen lockfile)
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: pnpm -r build
